### PR TITLE
Simplify Debian/Ubuntu packaging (fix #26)

### LINKED ISSUE #26: Simplify Debian & Ubuntu packaging
Could the project just have a single version of the packaging committed, compatible with current Debian stable and current Ubuntu LTS? If so, the focal packaging would be a good place to start. I see this was the only version updated anyway recently when a new release was made.

(Also I note that `compat` is wrong for focal: says `9`, should say `11`; I'll fix that!)

### PR DESCRIPTION
**Pull request by rrthomas**
* Only have one set of packaging files, initially those from ubuntu-focal,
  which was the most up-to-date set. It should work for current Debian &
  Ubuntu LTS. Put them in the standard “debian” subdirectory.
* Update debian/compat to 11, to match the debhelper Depends.
* Have a single build script, scripts/build-deb.sh, based on
  build-ubuntu.sh.
* Simplify the build script: make it POSIX sh-compatible rather than
  bash-specific, and use a single directory for its output, rather than two.

### CODE REVIEW

**Comment by rrthomas** [comment]
I hope this is OK. It should be simpler to use both for you, and for users who want to build packages for themselves (e.g. on Debian or derivatives). Given the recent update to the packaging, it would be good to have a new package release!

I maintain Launchpad packages which are built for multiple Ubuntu releases from a single set of packaging files, so it should be OK going forwards even if you want to build for all active Ubuntu releases. Happy to help fix any teething problems.

**Comment by tarickb** [comment]
Sorry for the delay here. What confuses me about this approach (namely, having just one changelog for all releases) is: aren't the packaging/release tools looking at the first line of the changelog to determine what Ubuntu/Debian release to target? How would one changelog allow us to target different Ubuntu/Debian releases?

**Comment by rrthomas** [comment]
The idea is that the packaging should work for Launchpad (which is targeting Ubuntu). (I didn't see any evidence of regular Debian releases.) Ideally `sasl-xoauth2` would be packaged in Debian (I'm happy to file a RTP bug if you like); but if you did want to make regular releases for Debian, then I would simply template the changelog file.

**Comment by tarickb** [comment]
Fair enough. I [manually built some packages](https://github.com/tarickb/sasl-xoauth2/issues/1) for Debian at one point in the past, but it'd be good to do this more regularly. I'm not at all familiar with the process there but if you are, and you're willing to take this on, I'd love the help!

**Comment by rrthomas** [comment]
I have filed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006888

**Comment by tarickb** [comment]
Awesome, thanks!

**Pull request merged**
